name: "DEV DEPLOY"

on:
  push:
    branches:
      - development

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::332479401705:role/github-actions-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "sa-east-1-terraform-lock"